name: Test Self Hosted Runner
on: [ workflow_dispatch ]

jobs:
  echo-test:
    runs-on: self-hosted
    steps:
      - name: Echo Hostname
        run: |
          echo "Hello world from Runner"
          echo $(hostname)