name: Check and create runner
on: [push]

jobs:
  install-runner:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
  
      - name: Check runner
        id: check-runner
        uses: redhat-actions/check-self-hosted-runner@main
        with:
          github_pat: ${{ secrets.PAT }}

      - name: Login Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: diagrawa-code

      - name: Create Self Hosted Runner
        if: steps.check-runner.outputs.runner_present == 'false'
        id: create-runner
        uses: ./
        with:
          github_pat: ${{ secrets.PAT }}
          runner_location: divyansh42/create-runner
          runner_name: actions-runner
      
      - name: Trigger Test workflow
        if: steps.create-runner.outputs.runner_created == 'true'
        uses: actions/github-script@v3
        id: trigger-workflow
        with: 
          github-token: ${{ secrets.PAT }}
          debug: true
          script: |
            await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'hello-world.yaml',
                ref: 'main'
            })
          
      - name: Get result
        run: echo "${{steps.trigger-workflow.outputs.result}}"
